various: some changes to autostart and workspace

diff --git a/bin/setup-system b/bin/setup-system
--- a/bin/setup-system
+++ b/bin/setup-system
@@ -1,16 +1,16 @@
 #!/bin/bash
 
 REQUIRED_TOOLS=(
-    curl
-    snap
-    apt
+  curl
+  snap
+  apt
 )
 
 for tool in "${REQUIRED_TOOLS[@]}"; do
-    if ! command -v "${tool}" >/dev/null; then
-        echo "${tool} is required... "
-        exit 1
-    fi
+  if ! command -v "${tool}" >/dev/null; then
+    echo "${tool} is required... "
+    exit 1
+  fi
 done
 
 # echo "Enter the sudo password, please"
@@ -19,8 +19,8 @@ done
 echo "Setup programs via APT"
 sudo apt purge libreoffice
 sudo apt install inkscape gimp build-essential atop htop i3 neofetch polybar \
-    feh dunst vim default-jdk libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev \
-    librsvg2-dev curl golang git shutter
+  feh dunst vim default-jdk libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev \
+  librsvg2-dev curl golang git shutter
 
 echo "Setup programs via Snap"
 sudo snap install todoist
@@ -36,11 +36,11 @@ nvm install node
 
 echo "Installing global NPM packages"
 npm -g install \
-    svgo cypress fixpack jshint \
-    lerna-wizard lerna lighthouse \
-    netlify-cli npm-check-updates \
-    svgo typescript \
-    @davidsneighbour/remark-config
+  svgo cypress fixpack jshint \
+  lerna-wizard lerna lighthouse \
+  netlify-cli npm-check-updates \
+  svgo typescript \
+  @davidsneighbour/remark-config
 
 echo "Installing Rust and Cargo"
 curl https://sh.rustup.rs -sSf | sh
@@ -78,3 +78,6 @@ echo "Completed in ${SECONDS}s"
 wget https://github.com/errata-ai/vale/releases/download/v2.15.4/vale_2.15.4_Linux_64-bit.tar.gz
 mkdir bin && tar -xvzf vale_2.15.4_Linux_64-bit.tar.gz -C bin
 export PATH=./bin:"$PATH"
+npm install -g aicommits
+
+npm i -g npkill
